[package]
name = "joycon"
version = "0.1.0"
authors = ["Alexander Peters <rainesabaal@gmail.com>"]

[dependencies]
hidapi = { git = "https://github.com/drola/hidapi-rs.git", branch = "linux-native-driver", features = ["linux-hidraw"]}
termion = "*"
lazy_static = "1.0.1"